package espacioUPM.Comunidades;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IAdministracionComunidad.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public interface IAdministracionComunidad {
	boolean modificarPermisos(String alias);
	
	boolean aceptarNuevoMiembro(String alias);
	
	boolean expulsarMiembro(String alias);
	
	boolean rechazarNuevoMiembro(String alias);
}
