//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Comunidad.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class Comunidad extends IAdministracionComunidad {
	private String nombre;
	public void Comunidad(String id, Usuario fundador) {
	
	}
	
	public void unirse(String alias) {
	
	}
	
	public void salir(String alias) {
	
	}
	
	public void visualizarTimelineCompartido() {
	
	}
	
	public String getNombre() {
	
	}
	
	public boolean modificarPermisos(Usuario usuario) {
	
	}
	
	public boolean aceptarNuevoMiembro(Usuario usuario) {
	
	}
	
	public boolean expulsarMiembro(Usuario usuario) {
	
	}
}
