//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IDB_Publicacion.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class IDB_Publicacion {
	public Publicacion getPublicacion(String id) {
	
	}
	
	public boolean setPublicacion(Publicacion publi) {
	
	}
	
	public Publicacion[] getPublicaciones(Usuario usuario) {
	
	}
	
	public boolean borrarPublicacion(Publicacion publi) {
	
	}
	
	public HashMap<String,Integer> puntuar(Usuario usuario, Publicacion publi, int puntuacion) {
	
	}
	
	public void comentar(Publicacion publi, Usuario usuario, String contenido) {
	
	}
}
