//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IDB_Usuario.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class IDB_Usuario {
	public Usuario getUsuario(String alias) {
	
	}
	
	public boolean setUsuario(Usuario usuario) {
	
	}
	
	public String[] getSeguidos(Usuario usuario) {
	
	}
	
	public String[] getSeguidores(Usuario usuario) {
	
	}
	
	public String cambiarAlias(Usuario usuario, String aliasNuevo) {
	
	}
	
	public boolean borrarUsuario(Usuario usuario) {
	
	}
	
	public boolean seguir(String seguidor, String seguido) {
	
	}
	
	public boolean dejarDeSeguir(String seguidor, String seguido) {
	
	}
}
