//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IDB_Comunidad.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class IDB_Comunidad {
	public boolean insertarMiembroComunidad(String id, String alias) {
	
	}
	
	public boolean borrarMiembroComunidad(String id, String alias) {
	
	}
	
	public boolean hacerAdminComunidad(String id, String alias) {
	
	}
	
	public Usuario[] getMiembros(Object comunidad Comunidad) {
	
	}
}
