//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IDB_Main.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class IDB_Main {
	public DB_Main getInstance() {
	
	}
}
