//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PublicacionTexto.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class PublicacionTexto extends Publicacion, Publicacion {
	private String contenido;
	public void PublicacionTexto(String autor, String contenido) {
	
	}
	
	public void mostrarPublicacion() {
	
	}
}
