//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PublicacionReferencia.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class PublicacionReferencia extends Publicacion {
	private Publicacion publicacionRef;
	public void PublicacionReferencia(String autor, String ref) {
	
	}
	
	public void mostrarPublicacion() {
	
	}
}
