//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Publicacion.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class Publicacion extends IPublicacion {
	private String IDPublicacion;
	private String autor;
	private Date fecha;
	private ArrayList<Comentario> comentarios;
	private int numLikes;
	private int numDislikes;
	public void verComentarios() {
	
	}
	
	public void comentar(Usuario autor, String contenido) {
	
	}
	
	public void like(Usuario usuario) {
	
	}
	
	public void dislike(Usuario usuario) {
	
	}
	
	public void mostrarPublicacion() {
	
	}
	
	public void Publicacion(String autor) {
	
	}
	
	public void referenciar(Usuario usuario) {
	
	}
}
