//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PublicacionEnlace.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class PublicacionEnlace extends Publicacion, Publicacion {
	private String url;
	public void PublicacionEnlace(String autor, String url) {
	
	}
	
	public void mostrarPublicacion() {
	
	}
}
