//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class Usuario {
	private String alias;
	private String correoUPM;
	public void darseDeBaja() {
	
	}
	
	public void Usuario(String alias) {
	
	}
	
	public void escribirPublicacion() {
	
	}
	
	public boolean borrarPublicacion(Publicacion publi) {
	
	}
	
	public void visualizarTimeline() {
	
	}
	
	public void visualizarPerfil() {
	
	}
	
	public void logout() {
	
	}
	
	public void buscar() {
	
	}
}
