package espacioUPM.Usuarios;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//


import espacioUPM.Database.IDB_PasswordHandler;
import espacioUPM.Database.IDB_Publicacion;
import espacioUPM.Database.IDB_Usuario;
import espacioUPM.Publicaciones.IPublicacion;
import javafx.beans.property.DoubleProperty;

public class Usuario implements IUsuario {

    private String alias;
    private static final IDB_Publicacion DB_publicacion = IDB_Publicacion.getInstance();
    private static final IDB_Usuario DB = IDB_Usuario.getInstance();
    private static final IDB_PasswordHandler DB_pass = IDB_PasswordHandler.getInstance();

    public Usuario(String alias) {
        this.alias = alias;
    }

    public static IUsuario getUsuario(String alias) {
        return DB.getUsuario(alias);
    }

    public static void setUsuario(String alias, String correo, String passwd) {
        DB.setUsuario(alias, correo, passwd);
    }

    public static IUsuario[] buscar(String alias) {
        return DB.buscarUsuario(alias);
    }

    public boolean comprobarPasswd(String pass) {
        return DB_pass.comprobarPasswd(alias, pass);
    }

    public boolean sigueA(String aliasSeguido) {
        return DB.estaSiguiendo(this.alias, aliasSeguido);
    }

    public void seguir(String aliasSeguido) {
        DB.seguir(alias, aliasSeguido);
    }

    public void dejarDeSeguir(String aliasSeguido) {
        DB.dejarDeSeguir(alias, aliasSeguido);
    }

    public String[] getSeguidos() {
        return DB.getSeguidos(this);
    }

    public String[] getSeguidores() {
        return DB.getSeguidores(this);
    }

    public IPublicacion[] obtenerPerfil(DoubleProperty progressProp) {
        return DB_publicacion.getPublicaciones(this, progressProp);
    }

    public String getAlias() {
        return alias;
    }

    public boolean cambiarAlias(String aliasNuevo) {
        return DB.cambiarAlias(this, aliasNuevo);
    }

    public void borrarDatos() {
        for(IPublicacion publi : DB_publicacion.getPublicaciones(this, null)) {
            DB_publicacion.borrarPublicacion(publi.getIDPublicacion());
        }
        DB.borrarComentarios(this);
        DB.borrarComunidades(this);
    }

    public void borrar() {
        DB.borrarUsuario(this);
    }
}
