package espacioUPM.Publicacion;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PublicacionTexto.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//


import java.time.LocalDateTime;
import java.util.ArrayList;

public class PublicacionTexto extends Publicacion {
	private String txt;

	PublicacionTexto(String idPublicacion, String autor, LocalDateTime fecha, ArrayList<Comentario> comentarios, int numLikes, int numDislikes, String txt) {
		super(idPublicacion, autor, fecha, comentarios, numLikes, numDislikes);
		this.txt = txt;
	}

	PublicacionTexto(String autor, String txt) {
		super(autor);
		this.txt = txt;
	}
	
	public void mostrarPublicacion() {
	
	}

	public String getContenido() {
		return txt;
	}
}
