package espacioUPM.Publicacion;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PublicacionEnlace.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//


import java.time.LocalDateTime;
import java.util.ArrayList;

public class PublicacionEnlace extends Publicacion {
	private String url;

	PublicacionEnlace(String idPublicacion, String autor, LocalDateTime fecha, ArrayList<Comentario> comentarios,
							 int numLikes, int numDislikes, String url) {
		super(idPublicacion, autor, fecha, comentarios, numLikes, numDislikes);
		this.url = url;
	}

	PublicacionEnlace(String autor, String url) {
		super(autor);
		this.url = url;
	}
	
	public void mostrarPublicacion() {
	
	}
}
