package espacioUPM.Database;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IDB_Usuario.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//


import espacioUPM.Usuario;

public interface IDB_Usuario {
	 Usuario getUsuario(String alias);
	
	 boolean setUsuario(Usuario usuario);

	 boolean setUsuario(String alias, String correo, byte[] password, byte[] salt);
	
	 String[] getSeguidos(Usuario usuario);
	
	 String[] getSeguidores(Usuario usuario);
	
	 boolean cambiarAlias(Usuario usuario, String aliasNuevo);
	
	 boolean borrarUsuario(Usuario usuario);
	
	 boolean seguir(String seguidor, String seguido);
	
	 boolean dejarDeSeguir(String seguidor, String seguido);
}
