package espacioUPM.Database;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IDB_Comunidad.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//


import espacioUPM.Comunidad;
import espacioUPM.Publicaciones.Publicacion;
import espacioUPM.Usuario;

public interface IDB_Comunidad extends IDB_Usuario {
	boolean insertarMiembroComunidad(String id, String alias);

	boolean aceptarMiembroComunidad(String id, String alias);
	
	boolean borrarMiembroComunidad(String id, String alias);
	
	boolean hacerAdminComunidad(String id, String alias);
	
	Usuario[] getMiembros(Comunidad comunidad);

	Publicacion[] getTimeline(Comunidad comunidad);
}
