package espacioUPM.Publicaciones;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IComentario.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public interface IComentario {
	String getAutor();
	
	String getContenido();

	String getPublicacionMadre();
}
