package espacioUPM.Publicaciones;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PublicacionReferencia.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//


import java.time.LocalDateTime;
import java.util.ArrayList;

public class PublicacionReferencia extends Publicacion {
	private Publicacion publicacionRef;

	PublicacionReferencia(String idPublicacion, String autor, LocalDateTime fecha, ArrayList<Comentario> comentarios, int numLikes, int numDislikes, Publicacion pub) {
		super(idPublicacion, autor, fecha, comentarios, numLikes, numDislikes);
		publicacionRef = pub;
	}

	PublicacionReferencia(String autor, Publicacion ref) {
		super(autor);
		this.publicacionRef = ref;
	}
	
	public void mostrarPublicacion() {
	
	}

	public Publicacion getPublicacionRef() {
		return publicacionRef;
	}
}
