package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Comentario.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class Comentario extends IComentario {
	private String autor;
	private Object contenido: String;
	public void Comentario(String autor, String contenido) {
	
	}
	
	public String getAutor() {
	
	}
	
	public String getContenido() {
	
	}
}
