package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Comunidad.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class Comunidad implements IAdministracionComunidad {
	private String nombre;
	private static final IDB_Comunidad DB = DB_Main.getInstance();

	public Comunidad(String id, Usuario fundador) {
		nombre = id;
		DB.hacerAdminComunidad(id, fundador.getAlias());

	}
	
	public void unirse(String alias) {
		DB.insertarMiembroComunidad(nombre, alias);
	}
	
	public void salir(String alias) {
		DB.borrarMiembroComunidad(nombre, alias);
	}
	
	public void visualizarTimelineCompartido() {
	
	}
	
	public String getNombre() {
		return nombre;
	}
	@Override
	public boolean aceptarNuevoMiembro(String alias) {
		return DB.aceptarMiembroComunidad(nombre, alias);
	}

	@Override
	public boolean rechazarNuevoMiembro(String alias) {
		return false;
	}

	@Override
	public boolean expulsarMiembro(String alias) {
		return DB.borrarMiembroComunidad(nombre, alias);
	}

	@Override
	public boolean modificarPermisos(String alias) {
		return DB.hacerAdminComunidad(nombre, alias);
	}
}
