package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Comunidad.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//
import java.util.Random;

public class Comunidad implements IAdministracionComunidad {
	private String nombre;
	private static final IDB_Comunidad DB = DB_Main.getInstance();

	public Comunidad(String id, Usuario fundador) {
		nombre = id;
		DB.hacerAdminComunidad(id, fundador.getAlias());

	}
	
	public boolean unirse(String alias) {
		return DB.insertarMiembroComunidad(nombre, alias);
	}
	
	public boolean salir(String alias) {
		return DB.borrarMiembroComunidad(nombre, alias);
	}
	
	public Publicacion[] visualizarTimelineCompartido() {
		Publicacion[] ret = new Publicacion[50];
		Usuario[] usuarios = DB.getMiembros(this);
		Random r = new Random();
		for (int i = 0; i < 50; i++) {
			//la idea es que genere 50 publicaciones de los miembros cogidos al azar
			//al azar los miembros, no las publicaciones.
			//las publicaciones deberían ser las más recientes de cada miembro
			//(getPublicaciones de un usuario las devuelve ordenadas por fecha)
		}
		return ret;
	}
	
	public String getNombre() {
		return nombre;
	}

	@Override
	public boolean aceptarNuevoMiembro(String alias) {
		return DB.aceptarMiembroComunidad(nombre, alias);
	}

	@Override
	public boolean rechazarNuevoMiembro(String alias) {
		return false;
	}

	@Override
	public boolean expulsarMiembro(String alias) {
		return DB.borrarMiembroComunidad(nombre, alias);
	}

	@Override
	public boolean modificarPermisos(String alias) {
		return DB.hacerAdminComunidad(nombre, alias);
	}
}
