package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Comunidad.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//
import espacioUPM.Database.DB_Main;
import espacioUPM.Database.IDB_Comunidad;
import espacioUPM.Publicaciones.Publicacion;

import java.util.ArrayList;

public class Comunidad implements IAdministracionComunidad {
	private String nombre;
	private String fundador;
	private static final IDB_Comunidad DB = DB_Main.getInstance();

	public Comunidad(String id, IUsuario fundador) {
		nombre = id;
		this.fundador = fundador.getAlias();
		DB.hacerAdminComunidad(id, fundador.getAlias());
	}

	public static Comunidad[] buscar(String id) {
		return DB.buscarComunidad(id);
	}
	public boolean unirse(String alias) {
		return DB.insertarMiembroComunidad(nombre, alias);
	}
	
	public boolean salir(String alias) {
		return DB.borrarMiembroComunidad(nombre, alias);
	}
	
	public Publicacion[] visualizarTimelineCompartido(int pagina) {
		ArrayList<Publicacion> ret = new ArrayList<>();
		Publicacion[] publicaciones = DB.getTimeline(this);
		for (int i = pagina*50, j = 0; i < publicaciones.length && j < 50; i++, j++)
			ret.add(publicaciones[i]);
		return (Publicacion[])ret.toArray();
	}
	
	public String getNombre() {
		return nombre;
	}

	@Override
	public boolean aceptarNuevoMiembro(String alias) {
		return DB.aceptarMiembroComunidad(nombre, alias);
	}

	@Override
	public boolean rechazarNuevoMiembro(String alias) {
		return false;
	}

	@Override
	public boolean expulsarMiembro(String alias) {
		return DB.borrarMiembroComunidad(nombre, alias);
	}

	@Override
	public boolean modificarPermisos(String alias) {
		return DB.hacerAdminComunidad(nombre, alias);
	}

	public String getFundador() {
		return fundador;
	}
}
