package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DB_Main.java
//  @ Date : 5/9/2019
//  @ Author :
//
//

import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;

public class DB_Main implements IDB_Usuario, IDB_Comunidad, IDB_Publicacion {
    private Connection connection;
    private static DB_Main instancia;
    private  DB_Main() {

        try {
            connection = DriverManager.getConnection("jdbc:mysql://37.187.200.26:3307/twitter2?user=serv&password=Habichuelas73");
            System.out.println("[+] DB Conectada.");
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    public static DB_Main getInstance() {

        if (instancia == null) {
            instancia = new DB_Main();
        }
        return instancia;

    }

    public Usuario getUsuario(String alias) {

        try (PreparedStatement pStmt = connection.prepareStatement("SELECT * FROM `Usuarios` WHERE `alias` = ?"))
        {
            pStmt.setString(1, alias);


            ResultSet ret = pStmt.executeQuery();

            return ret.next() ? new Usuario(ret.getString("alias")) : null;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;

    }

    @Override
    public boolean setUsuario(Usuario usuario) {
        return false;
    }

    public boolean setUsuario(String alias, String correo, byte[] password, byte[] salt) {
        try (PreparedStatement pStmt = connection.prepareStatement("INSERT INTO `Usuarios` VALUES (NULL, ?, ?, ?, ?)")) {
            pStmt.setString(1, alias);
            pStmt.setString(2, correo);
            pStmt.setBytes(3, password);
            pStmt.setBytes(4, salt);

            return pStmt.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;

    }

    public boolean setPublicacion(Publicacion publi) {


        try (PreparedStatement pStmt = connection.prepareStatement("INSERT INTO `publicaciones` VALUES (NULL, ?, ?, ?, ?)")) {
            pStmt.setString(1, publi.getAutor());
            pStmt.setString(2, publi.getFecha().toString());
            if (publi instanceof PublicacionTexto) {
                pStmt.setString(3, ((PublicacionTexto) publi).getContenido());
                pStmt.setNull(3, Types.VARCHAR);
            } else {
                    pStmt.setInt(4, Integer.decode(((PublicacionReferencia)publi).getPublicacionRef().getIDPublicacion()));
                    pStmt.setNull(4, Types.INTEGER);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;

    }
    
    public Publicacion getPublicacion(String id) {
        Publicacion ret = null;
        try {
            PreparedStatement statement = connection.prepareStatement("SELECT * FROM publicaciones WHERE id = ?");
            statement.setString(1, id);
            ResultSet rs = statement.executeQuery();
            if(rs.next()) {
                String autor = rs.getString("autor");

                String cuerpo = rs.getString("id_ref") != null ?
                        rs.getString("id_ref") :
                        rs.getString("cuerpo");

                LocalDateTime date = LocalDateTime.parse(rs.getString("fecha"));
                ArrayList<Comentario> comentarios = getComentarios(id);
                int numLikes = getLikes(id);
                int numDislikes = getDislikes(id);
                ret = PublicacionFactory.createPublicacion(id, cuerpo, autor, date, comentarios, numLikes, numDislikes);
            }
        }
        catch(SQLException e) { e.printStackTrace(); }

        return ret;
    }


    public Publicacion[] getPublicaciones(Usuario usuario) {

        try (PreparedStatement pStmt = connection.prepareStatement("SELECT id FROM publicaciones WHERE autor = ?"))
        {
            pStmt.setString(1, usuario.getAlias());
            ResultSet rs = pStmt.executeQuery();
            ArrayList<Publicacion> ret = new ArrayList<>();
            while(rs.next()) {
                ret.add(getPublicacion(rs.getString("id")));
            }
            return ret.toArray(Publicacion[]::new);
        }
        catch (SQLException e) { e.printStackTrace(); }

        return null;
    }

    //DONE
    public ArrayList<Comentario> getComentarios(String publication_id) {
        ArrayList<Comentario> ret = new ArrayList<>();
        try {
            PreparedStatement comentarios = connection.prepareStatement("SELECT * FROM comentarios WHERE id_publicacion = ?");
            comentarios.setString(1, publication_id);
            ResultSet rs = comentarios.executeQuery();
            while(rs.next()) {
                String autor = rs.getString("alias");
                String contenido = rs.getString("texto");
                ret.add(new Comentario(autor,contenido,publication_id));
            }
        }
        catch(SQLException e) { e.printStackTrace(); }

        return ret;
    }

    //DONE
    public int getLikes(String publication_id) {
        try{
            PreparedStatement statement = connection.prepareStatement("SELECT COUNT (*) AS numero FROM likes WHERE id_publicacion = ? AND valor = 1");
            statement.setString(1, publication_id);
            return statement.executeQuery().getInt("numero");
        }
        catch(SQLException e) { e.printStackTrace(); }
        return 0;
    }

    //DONE
    public int getDislikes(String publication_id) {
        try{
            PreparedStatement statement = connection.prepareStatement("SELECT COUNT (*) AS numero FROM likes WHERE id_publicacion = ? AND valor = -1");
            statement.setString(1, publication_id);
            return statement.executeQuery().getInt("numero");
        }
        catch(SQLException e) { e.printStackTrace(); }
        return 0;
    }

    public boolean borrarPublicacion(Publicacion publi) {
        try (PreparedStatement pStmt = connection.prepareStatement("DROP * FROM publicaciones WHERE id = ?"))
        {
            pStmt.setInt(1, Integer.decode(publi.getIDPublicacion()));
            pStmt.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return true;
    }

    public String[] getSeguidos(Usuario usuario) {
        ArrayList<String> ret = new ArrayList<>();
        try (PreparedStatement pStmt = connection.prepareStatement("SELECT * FROM seguimiento WHERE seguidor = ?")) {
            pStmt.setString(1, usuario.getAlias());

            ResultSet cur = pStmt.executeQuery();

            while (cur.next())
                ret.add(cur.getString("alias"));

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return ret.toArray(String[]::new);
    }

    public String[] getSeguidores(Usuario usuario) {
        ArrayList<String> ret = new ArrayList<>();
        try (PreparedStatement pStmt = connection.prepareStatement("SELECT * FROM seguimiento WHERE seguido = ?")) {
            pStmt.setString(1, usuario.getAlias());

            ResultSet cur = pStmt.executeQuery();

            while (cur.next())
                ret.add(cur.getString("alias"));

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return ret.toArray(String[]::new);
    }

    public boolean cambiarAlias(Usuario usuario, String aliasNuevo) {
        try (PreparedStatement pStmt = connection.prepareStatement("UPDATE usuarios SET alias = ? WHERE alias = ?")) {
            pStmt.setString(1, aliasNuevo);
            pStmt.setString(2, usuario.getAlias());
            pStmt.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return true;
    }

    @Override
    public boolean borrarUsuario(Usuario usuario) {
        try (PreparedStatement pStmt = connection.prepareStatement("DELETE FROM usuarios WHERE alias = ?")) {
            pStmt.setString(1, usuario.getAlias());
            pStmt.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return true;
    }

    public boolean borrarMiembroComunidad(String id, String alias) {
        try (PreparedStatement pStmt = connection.prepareStatement("DELETE FROM miembros_comunidad WHERE id_usuario = ? AND id_comunidad = ?")) {
            pStmt.setString(1, alias);
            pStmt.setString(2, id);
            pStmt.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return true;
    }

    public boolean insertarMiembroComunidad(String id, String alias) {
        try (PreparedStatement pStmt = connection.prepareStatement("INSERT INTO miembros_comunidad VALUES (?, ?, ?)")) {
            pStmt.setString(1, alias);
            pStmt.setString(2, id);
            pStmt.setBoolean(3, false);
            pStmt.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return true;
    }

    public boolean seguir(String seguidor, String seguido) {
        try (PreparedStatement pStmt = connection.prepareStatement("INSERT INTO seguimiento VALUES (?, ?)")){
            pStmt.setString(1, seguidor);
            pStmt.setString(2, seguido);
            pStmt.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return true;

    }

    public boolean dejarDeSeguir(String seguidor, String seguido) {
        try (PreparedStatement pStmt = connection.prepareStatement("DELETE FROM seguimiento WHERE seguidor = ? AND seguido = ?")) {
            pStmt.setString(1, seguidor);
            pStmt.setString(2, seguido);
            pStmt.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return true;

    }

    public boolean puntuar(Usuario usuario, Publicacion publi, int puntuacion) {
        try (PreparedStatement pStmt = connection.prepareStatement("INSERT INTO likes VALUES (?, ?, ?)")) {
            pStmt.setString(1, usuario.getAlias());
            pStmt.setInt(2, puntuacion);
            pStmt.setInt(3, Integer.decode(publi.getIDPublicacion()));
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return true;

    }

    public boolean hacerAdminComunidad(String id, String alias) {
        try (PreparedStatement pStmt = connection.prepareStatement("UPDATE miembros_comunidad SET admin = 1 WHERE id_comunidad = ? AND id_usuario = ?")) {
            pStmt.setString(1, alias);
            pStmt.setString(2, id);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return true;
    }

    @Override
    public Usuario[] getMiembros(Comunidad comunidad) {
        ArrayList<Usuario> ret = new ArrayList<>();
        try (PreparedStatement pStmt = connection.prepareStatement("SELECT * FROM miembros_comunidad WHERE id_comunidad = ?")) {
            pStmt.setString(1, comunidad.getNombre());

            ResultSet cur = pStmt.executeQuery();

            while (cur.next()) {
                ret.add(getUsuario(cur.getString("id_usuario")));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return ret.toArray(Usuario[]::new);
    }

    public void comentar(Publicacion publi, Usuario usuario, String contenido) {
        try (PreparedStatement pStmt = connection.prepareStatement("INSERT INTO comentarios VALUES (NULL, ?, ?, ?)")) {
            pStmt.setString(1, usuario.getAlias());
            pStmt.setString(2, contenido);
            pStmt.setInt(3, Integer.decode(publi.getIDPublicacion()));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
