package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IAdministracionComunidad.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class IAdministracionComunidad {
	public boolean modificarPermisos(String alias) {
	
	}
	
	public boolean aceptarNuevoMiembro(String alias) {
	
	}
	
	public boolean expulsarMiembro(String alias) {
	
	}
	
	public boolean rechazarNuevoMiembro(String alias) {
	
	}
}
