package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IComentario.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class IComentario {
	public String getAutor() {
	
	}
	
	public String getContenido() {
	
	}
}
