package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IDB_Comunidad.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public interface IDB_Comunidad {
	boolean insertarMiembroComunidad(String id, String alias);
	
	boolean borrarMiembroComunidad(String id, String alias);
	
	boolean hacerAdminComunidad(String id, String alias);
	
	Usuario[] getMiembros(Comunidad comunidad);
}
