package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IDB_Publicacion.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//

public interface IDB_Publicacion {

	String getNewID();
	Publicacion getPublicacion(String id);

	boolean setPublicacion(Publicacion publi);

	Publicacion[] getPublicaciones(Usuario usuario);
	
	boolean borrarPublicacion(Publicacion publi);
	
	boolean puntuar(Usuario usuario, Publicacion publi, int puntuacion);
	
	void comentar(Publicacion publi, Usuario usuario, String contenido);

}
