package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IPublicacion.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public interface IPublicacion {
	void verComentarios();
	
	void comentar(Usuario autor, String contenido);
	void like(Usuario usuario);
	
	void dislike(Usuario usuario);
	
	void referenciar(Usuario usuario);
}
