package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IPublicacion.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class IPublicacion {
	public void verComentarios() {
	
	}
	
	public void comentar(Usuario autor, String contenido) {
	
	}
	
	public void like(Usuario usuario) {
	
	}
	
	public void dislike(Usuario usuario) {
	
	}
	
	public void referenciar(Usuario usuario) {
	
	}
}
