package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PasswordHandler.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class PasswordHandler {
	public void comprobarPasswd(String alias, String passwd) {
	
	}
	
	private byte[] hash(String txt, byte[] salt) {
	
	}
}
