package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PublicacionFactory.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//



public class PublicacionFactory {
	public void createPublicacion(data : String) : Publicacion() {
	
	}
}
