package espacioUPM;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 5/9/2019
//  @ Author : 
//
//


import espacioUPM.Publicaciones.Publicacion;

public class Usuario {
	private String alias;
	public void darseDeBaja() {
	
	}
	
	public Usuario(String alias) {
	    this.alias = alias;
	}
	
	public void escribirPublicacion() {
	
	}
	
	public boolean borrarPublicacion(Publicacion publi) {
	    return true;
	}
	
	public void visualizarTimeline() {
	
	}
	
	public void visualizarPerfil() {
	
	}
	
	public void logout() {
	
	}
	
	public void buscar() {
	
	}

    public String getAlias() {
        return alias;
    }
}
